#!/bin/sh

APPDIR=$(greadlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/LEDWALL_MACOS.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/nrserial.jar:$APPDIR/lib/PixelPusher.jar" LEDWALL_MACOS LEDWall_DumbRain_CommandLine --image-width 400 --image-height 300 --num-panels-x 1 --num-panels-y 1 --screen-saver 2 --canvas-width 800 --canvas-height 800 --image-filename testing.jpg
